#!/bin/bash
# TODO we need a cgi handler, people might pass parameters to grasp script from QUERY_STRING
if [ "$#" -lt 1 ]; then
    echo "Needs one argument: The grasp file"
    exit 1
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
python ${DIR}/grasp.py $1 || exit 1
${DIR}/stackmachine.out $1o
