#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Needs one argument: The grasp file"
    exit 1
fi
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
python ${DIR}/grasp.py $1 || exit 1
${DIR}/stackmachine.out $1o
